# Generated by Django 4.0.3 on 2022-03-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('Dermatologist', 'Dermatologist'), ('Psychiatrist', 'Psychiatrist'), ('Neurologist', 'Neurologist'), ('Physician', 'Physician')], max_length=20),
        ),
    ]
